#!/usr/bin/env python3

from shlib import lsf, Run, set_prefs, to_path
from inform import Error
set_prefs(use_inform=True)

golden = to_path('Golden')

for py_file in lsf(select='*.py'):
    print(str(py_file))
    cmd = ['python3', py_file]
    try:
        Run(cmd, 'soEW')
    except Error as e:
        e.report()

if golden.exists():
    for svg_file in lsf(select='*.svg'):
        cmd = ['cmp', svg_file, golden / svg_file]
        try:
            Run(cmd, 'soEW')
        except Error as e:
            e.report()
