#!/usr/bin/env python3

from svg_schematic import (
    Schematic, offsets_to_coordinates, shift_x, shift_y, shift,
    Capacitor, Diode, Ground, Pin, Wire
)

with Schematic(filename = "charge-pump.svg", line_width=2, background='none'):

    x_offsets = dict(
        i = 0,
        d1 = 75,
        c1 = 75,
        d2 = 75,
        c2 = 75,
        d3 = 75,
        c3 = 75,
        d4 = 75,
        c4 = 75,
        d5 = 75,
        c5 = 75,
        o = 75
    )
    y_offsets = dict(
        d = 0,
        c = 75,
        p1 = 75,
        p2 = 50
    )
    offsets_to_coordinates(locals(), x_offsets, y_offsets)

    vin = Pin((i_x, d_y), kind='in', name=r'$V_{\rm in}$', w=2)
    p1 = Pin((i_x, p1_y), kind='in', name=r'$\phi_1$', w=2)
    p2 = Pin((i_x, p2_y), kind='in', name=r'$\phi_2$', w=2)
    d1 = Diode((d1_x, d_y), orientation='h')
    c1 = Capacitor((c1_x, c_y), orientation='v')
    d2 = Diode((d2_x, d_y), orientation='h')
    c2 = Capacitor((c2_x, c_y), orientation='v')
    d3 = Diode((d3_x, d_y), orientation='h')
    c3 = Capacitor((c3_x, c_y), orientation='v')
    d4 = Diode((d4_x, d_y), orientation='h')
    c4 = Capacitor((c4_x, c_y), orientation='v')
    d5 = Diode((d5_x, d_y), orientation='h')
    c5 = Capacitor((c5_x, c_y), orientation='v')
    vout = Pin((o_x, d_y), kind='out', name=r'$V_{\rm out}$', w=2)
    Ground(c5.t[1])

    Wire([vin.t[0], d1.t[0]])
    Wire([d1.t[1], d2.t[0]])
    Wire([d2.t[1], d3.t[0]])
    Wire([d3.t[1], d4.t[0]])
    Wire([d4.t[1], d5.t[0]])
    Wire([d5.t[1], vout.t[0]])
    Wire([(c1_x, d_y), c1.t[0]])
    Wire([(c2_x, d_y), c2.t[0]])
    Wire([(c3_x, d_y), c3.t[0]])
    Wire([(c4_x, d_y), c4.t[0]])
    Wire([(c5_x, d_y), c5.t[0]])
    Wire([(c1_x, p1_y), c1.t[1]])
    Wire([(c2_x, p2_y), c2.t[1]])
    Wire([p1.t[0], (c3_x, p1_y), c3.t[1]])
    Wire([p2.t[0], (c4_x, p2_y), c4.t[1]])
