#!/usr/bin/env python3

from schematic import (
    Schematic, offsets_to_coordinates, shift_x, shift_y, shift,
    MOS, Ground, Gate, Label, Pin, Wire
)

with Schematic(filename = 'inverter.svg', line_width=2, background='none'):

    x_offsets = dict(
        vin = 0,
        m = 100,
        vout = 100,
    )
    y_offsets = dict(
        vdd = 0,
        mp = 75,
        vin = 50,
        mn = 50,
        gnd = 75,
        dig = 25,
    )
    offsets_to_coordinates(locals(), x_offsets, y_offsets)

    vin = Pin((vin_x, vin_y), kind='in', name=r'$V_{\rm in}$')
    mp = MOS((m_x, mp_y), kind='p')
    mn = MOS((m_x, mn_y), kind='n')
    vout = Pin((vout_x, vin_y), kind='out', name=r'$V_{\rm out}$')
    Label(mp.t[2], loc='n', name=r'$V_{\rm dd}$')
    Ground(mn.t[2])
    Wire([mp.t[0], mn.t[0]])
    Wire([(m_x+50, vin_y), vout.t[0]])
    Wire([(m_x-50, vin_y), vin.t[0]])
    Wire([mp.t[1], mn.t[1]])

    vin = Pin((vin_x, dig_y), kind='in', name=r'$V_{\rm in}$')
    inv = Gate((m_x, dig_y), kind='inv')
    vout = Pin((vout_x, dig_y), kind='out', name=r'$V_{\rm out}$')
    Wire([inv.t[0], vout.t[0]])
    Wire([inv.t[1], vin.t[0]])

