#!/usr/bin/env python3

try:
    from shlib import lsf, Run, set_prefs, to_path
    from inform import Error
    set_prefs(use_inform=True)
except ImportError:
    print(
        'Run `pip install --user -r requirements.txt`',
        'to install missing packages.'
    )
    raise SystemExit

golden = to_path('Golden')

for py_file in lsf(select='*.py'):
    print(str(py_file))
    cmd = ['python3', py_file]
    try:
        Run(cmd, 'soEW')
    except Error as e:
        e.report()

if golden.exists():
    for svg_file in lsf(select='*.svg'):
        cmd = ['cmp', svg_file, golden / svg_file]
        try:
            Run(cmd, 'soEW')
        except Error as e:
            e.report()
