#!/usr/bin/env python3

from schematic import (
    Schematic, offsets_to_coordinates, shift, shift_y, shift_x, with_x, with_y,
    Capacitor, MOS, Ground, Inductor, Label, Source, Wire,
)

with Schematic(filename = "oscillator.svg", background='none', line_width=2):
    x_offsets = dict(
        l = 0,
        c = 125,
        r = 125,
    )
    y_offsets = dict(
        t = 0,
        l = 50,
        c = 50,
        m = 125,
        i = 100,
    )
    offsets_to_coordinates(locals(), x_offsets, y_offsets)

    # resonator
    vdd = Label((c_x, t_y-25), loc='n', nudge=10, name=r'$V_{\rm dd}$')
    Wire([(c_x, t_y), (c_x, t_y-25)])
    ll = Inductor((l_x, l_y), orientation='v', name=r'$\frac{1}{2} L$')
    lr = Inductor((r_x, l_y), orientation='v|', name=r'$\frac{1}{2} L$')
    Wire([ll.p, lr.p])
    c = Capacitor((c_x, c_y), orientation='h', name='$C$')
    Wire([c.p, with_x(c.c, l_x)])
    Wire([c.n, with_x(c.c, r_x)])

    # gain stage
    ml = MOS(shift_x((l_x, m_y), 50), orientation='|')
    mr = MOS(shift_x((r_x, m_y), -50), orientation='')
    Wire([ll.n, ml.d])
    Wire([lr.n, mr.d])
    Wire([ml.g, shift_y(ml.g, -25), shift(ml.g, 50, -75), shift_y(mr.d, -25)])
    Wire([mr.g, shift_y(mr.g, -25), shift(mr.g, -50, -75), shift_y(ml.d, -25)])
    Wire([ml.s, mr.s])
    Source((c_x, i_y), kind='idc', value=r'$I_{\rm ss}$')

