#!/usr/bin/env python3

from schematic import (
    Schematic, shift, shift_x, shift_y, with_x, with_y, offsets_to_coordinates,
    Amp, Box, Ground, Label, Pin, Source, Wire
)

with Schematic(
    filename = 'receiver.svg',
    font_size = 12,
    font_family = 'sans',
    outline = 'orange',
    left_pad = 80,
    right_pad = 25,
    top_pad = 25,
    bottom_pad = 25
) as schematic:

    # Place input from horn at 0,0. Describe horn with labels on the west side.
    rf_in = Pin((0,0), kind='in')
    Label(rf_in.c, loc='w', name='L-band Horn')
    Label(shift_y(rf_in.c, 15), loc='w', name='fc=1420MHz')
    Label(shift_y(rf_in.c, 30), loc='w', name='BW=15MHz')

    # Place first preamp 75 units east of input. Amplifier is 100 units wide.
    # Place label south of preamp and connect wire from input to preamp.
    rf_preamp1 = Amp(shift_x(rf_in.c, 75), name='RF Preamp1')
    Label(rf_preamp1.s, loc='s', name='A>=26dB')
    Wire([rf_in.c, rf_preamp1.w])

    # Place second preamp 75 units east of first.
    rf_preamp2 = Amp(shift_x(rf_preamp1.e, 75), name='RF Preamp2')
    Label(rf_preamp2.s, loc='s', name='A>=26dB')
    Wire([rf_preamp1.e, rf_preamp2.w])

    # Place RF band-pass filter east of preamps.
    rf_bpf = Box(shift_x(rf_preamp2.e, 75), name='RF BPF')
    Label(rf_bpf.s, loc='s', name='fc=1380MHz')
    Label(shift_y(rf_bpf.s, 15), loc='s', name='BW=320MHz')
    Wire([rf_preamp2.e, rf_bpf.w])

    # Place first RF amplifier east of RF band-pass filter.
    rf_amp1 = Amp(shift_x(rf_bpf.e, 75), name='RF Amp1')
    Label(rf_amp1.s, loc='s', name='A<=20dB')
    Wire([rf_bpf.e, rf_amp1.w])

    # Place second RF amplifier east of first.
    rf_amp2 = Amp(shift_x(rf_amp1.e, 75), name='RF Amp2')
    Label(rf_amp2.s, loc='s', name='A<=20dB')
    Wire([rf_amp1.e, rf_amp2.w])

    # Place RF mixer east of amplifiers.
    rf_mixer = Source(shift_x(rf_amp2.e, 50), kind='mult')
    Label(rf_mixer.n, loc='n', name='DSB')
    Wire([rf_amp2.e, rf_mixer.w])

    # Place RF local oscillator south of RF mixer.
    rf_lo = Source(
        shift_y(rf_mixer.s, 100), kind='sine',
        name='fo=1230MHz', value='P=10dBm'
    )
    Ground(shift_y(rf_lo.s, 25))
    Wire([rf_mixer.s, rf_lo.n])

    # Place IF band-pass filter east of RF mixer.
    if_bpf = Box(shift_x(rf_mixer.e, 75), name='IF BPF')
    Label(if_bpf.s, loc='s', name='fc=190MHz')
    Label(shift_y(if_bpf.s, 15), loc='s', name='BW=22MHz')
    Wire([rf_mixer.e, if_bpf.w])

    # Place IF amplifier east of IF band-pass filter.
    if_amp = Amp(shift_x(if_bpf.e, 75), name='IF Amp')
    Label(if_amp.s, loc='s', name='A=20dB')
    Wire([if_bpf.e, if_amp.w])

    # Place IF mixer east of IF amplifier.
    if_mixer = Source(shift_x(if_amp.e, 50), kind='mult')
    Label(if_mixer.n, loc='n', name='SSB')
    Wire([if_amp.e, if_mixer.w])

    # Place IF local oscillator south of IF mixer.
    if_lo = Source(
        shift_y(if_mixer.s, 100), kind='sine',
        name='fo=190MHz', value='P=10dBm'
    )
    Ground(shift_y(if_lo.s, 25))
    Wire([if_mixer.s, if_lo.n])

    # Place baseband low-pass filter east of IF mixer.
    bb_lpf = Box(shift_x(if_mixer.e, 75), name='BB LPF')
    Label(bb_lpf.s, loc='s', name='BW=2MHz (var)')
    Wire([if_mixer.e, bb_lpf.w])

    # Place analog-to-digital converter east of baseband amplifier.
    adc = Box(shift_x(bb_lpf.e, 75), name='ADC')
    Label(adc.s, loc='s', name='Fclk=var')
    Wire([bb_lpf.e, adc.w])

    # Place output east of analog-to-digital converter.
    bb_out = Pin(shift_x(adc.e, 50), kind='out', name='out')
    Label(shift_x(adc.e, 25), kind='slash', loc='s', name='8')
    Wire([adc.e, bb_out.c])
