#!/usr/bin/env python3

from shlib import lsf, Run, set_prefs
from inform import Error, os_error
set_prefs(use_inform=True)

for py_file in lsf(select='*.py'):
    print(str(py_file))
    cmd = ['python3', py_file]
    Run(cmd, 'soEW')
